### ISSUE TITLE
completeByNoMore 在文档中描述有误

### ISSUE THREAD

**Issue by RyanCnn15** [SmileZXLee/uni-z-paging#101]
官网文档为：
- 参数1(必填):请求结果数组；
- 参数2(必填):是否有更多数据，若为true则可以继续滚动到底部加载更多，但如果在某个时刻参数1传入了空数组，也代表着没有更多数据了；
- 参数3(非必填):是否请求成功，不填默认为true

此处参数2描述有误，实际传入值为`false`时才可以请求下一页，更新了`2.4.0`后仍是此逻辑，请更正描述

**Comment by SmileZXLee** [comment]
你的文档是否是`z-paging.com`？这个网站文档已不更新了，推荐使用新域名[https://z-paging.zxlee.cn](https://z-paging.zxlee.cn)

**Comment by SmileZXLee** [comment]
我抽空也更新一下z-paging.com
