### ISSUE TITLE
开启了聊天记录模式use-chat-record-mode，进入页面后，列表是倒序的，但是没有自动滚动到底部，并且往上拉加载新数据时，页面也会跳到最顶部，而不是从加载的第一条开始看

### ISSUE THREAD

**Issue by seepine** [SmileZXLee/uni-z-paging#102]
**编译平台**
使用HbuilderX还是npm方式编译出现的问题？（如：HbuilderX）
npm
**VUE版本**
在vue2还是vue3中出现的问题，是nvue还是vue？（如：vue2+nvue）
vue3
**运行平台**
在运行到哪个平台中出现的问题？（如：App、微信小程序、h5）
h5
**z-paging版本**
在哪个版本的z-paging中出现的问题？
2.6.3
**问题描述**
请详细描述问题，最好说明复现步骤，尽可能附上代码或截图

**Comment by SmileZXLee** [comment]
未能复现 请试下demo是否有问题

**Comment by SmileZXLee** [comment]
2.7.0支持了非页面滚动滚动到顶部，可以更新一下此beta版本后再次尝试

**Comment by yuanteng666** [comment]
同样的问题。列表倒序我认为是正确的。但是后半句跟我也有同样的现象。比方说 顶部 是 数据 19，加载更多后直接就跳到了最顶部29的数据，而不是还在20/19位置。我这还有个问题就是空视图不显示。
z-paging 2.6.9 vue 3.0 hbx最新版。
`<template>
	<view class="content">
		<z-paging
			ref="paging"
			v-model="items"
			@query="queryList"
			use-chat-record-mode
		>
			<template #empty>
			    <image src="../../static/logo.png" class="logo" mode=""></image>
			</template>
			<template #top>
				<view class="headter">我是头</view>
			</template>
			<view class="item" v-for="(item, index) in items" :key="index">
				{{ item }}
			</view>

			<template #bottom>
				<input :adjust-position="dont" class="input" confirm-type="send" type="text" placeholder="请输入内容" @confirm="doSend" />
			</template>
		</z-paging>
	</view>
</template>

<script>
export default {
	data() {
		let keyyy = false;

		return {
			title: 'Hello',
			name: '我是',
		
			items: [],
			dont: keyyy,
			bottom: 0,
			isFocused: false,
			viewHeight: 0
		};
	},

	methods: {
		scrollToBootom() {
			this.$refs.paging.scrollToBottom();
		},
		
		queryList(pageNo, pageSize) {
			//组件加载时会自动触发此方法，因此默认页面加载时会自动触发，无需手动调用
			//这里的pageNo和pageSize会自动计算好，直接传给服务器即可
			//模拟请求服务器获取分页数据，请替换成自己的网络请求
			const params = {
				pageNo: pageNo,
				pageSize: pageSize
			};
			this.getdata().then((res) => {
				this.$refs.paging.setLocalPaging(res.totalList, res.noMore);
			});
		},
		getdata() {
			const ppp = new Promise((resolve, reject) => {
				let arr = [];
				for (var i = 0; i < 50; i++) {
					arr.push(i);
				}
				setTimeout(() => {
					resolve({
						totalList: arr,
						noMore: true
					});
				}, 300);
			});
			return ppp;
		},
		doSend() {
			uni.showLoading({
				title: '发送中...'
			});
			const valut = this.items.length + 1;
			console.log('va', valut);
			setTimeout(() => {
				uni.hideLoading();
				this.$refs.paging.addChatRecordData(valut);
				this.isFocused = false;
			}, 500);
		}
	}
};
</script>

<style>
.headter {
	background-color: aquamarine;
	padding: 20rpx;
	padding-top: 44px;
	text-align: center;
}
.content {
	display: flex;
	flex-direction: column;
}
.scroll {
	flex: 1;
	background-color: aqua;
}
.item {
	padding: 60rpx;
	font-size: 40rpx;
	text-align: center;
	border-bottom: 1rpx solid red;
}
.logo {
	height: 200rpx;
	width: 200rpx;
	margin-top: 200rpx;
	margin-left: auto;
	margin-right: auto;
	margin-bottom: 50rpx;
}

.text-area {
	display: flex;
	justify-content: center;
}

.title {
	font-size: 36rpx;
	color: #8f8f94;
}
.input {
	padding: 20rpx;
	line-height: 1;
	margin: 0 20rpx;
	margin-bottom: 60rpx;
	border-radius: 20rpx;
	border: 1px solid #8f8f94;
}
</style>
`

**Comment by SmileZXLee** [comment]
下个版本将采取新的方案以解决此问题

**Comment by SmileZXLee** [comment]
`v2.7.0`带来了全新设计的聊天记录模式，完全解决了聊天记录模式滚动加载更多闪动和微信小程序中，导航栏被顶上去的问题！欢迎更新体验！
