### ISSUE TITLE
请问 z-paging 该如何清空缓存？

### ISSUE THREAD

**Issue by kosuke-zhang** [SmileZXLee/uni-z-paging#103]
我们在个人中心页使用了 z-paging，在用户推出登录时、或者访问他人个人中心时如何清空 z-paging 内的缓存数据呢？

**Comment by SmileZXLee** [comment]
调用`this.$paging.clear()`清除列表数据

**Comment by kosuke-zhang** [comment]
🐮🐮🐮，您回复真及时呀，感谢感谢！

**Comment by SmileZXLee** [comment]
通过`uni.removeStorageSync(z-paging-cache-xxx)`来清除对应的缓存。或者在退出登录时直接`uni.clearStorageSync()`清除所有缓存

**Comment by kosuke-zhang** [comment]
好嘞，理解啦
