### ISSUE TITLE
【可复现】特定场景下无法滑动

### ISSUE THREAD

**Issue by kosuke-zhang** [SmileZXLee/uni-z-paging#104]
**编译平台**
HbuilderX

**VUE版本**
vue2+nvue

**运行平台**
App

**z-paging版本**
v2.6.x

**问题描述**

滑动切换选项卡+吸顶演示（nvue）

不使用自定义 refresher 时列表在吸顶之后无法继续上滑，使用自定义 refresher 列表可以继续上滑

https://github.com/SmileZXLee/uni-z-paging/assets/30019034/4ce27fbf-b6a9-4e11-92fb-9612dce0a034

**Comment by SmileZXLee** [comment]
你好，我在demo的`sticky-swiper-demo-n`中按照你提供的复现步骤尝试，未能复现，测试了几种可能的情况都是可以滚动的。劳烦在demo中试下哈或提供可复现demo

**Comment by kosuke-zhang** [comment]
> 你好，我在demo的`sticky-swiper-demo-n`中按照你提供的复现步骤尝试，未能复现，测试了几种可能的情况都是可以滚动的。劳烦在demo中试下哈或提供可复现demo

好嘞，我用 demo 看下
