### ISSUE TITLE
第一次加载时展示空白

### ISSUE THREAD

**Issue by CymuYae** [SmileZXLee/uni-z-paging#106]
**编译平台**
HbuilderX

**VUE版本**
vue3

**运行平台**
微信小程序

**z-paging版本**
2.6.2

**问题描述**
第一次进入时页面空白，未加载数据，感觉好像是闪了一下，有一瞬间可以看到数据，但又白了，试着setTimeout 1000ms可以解决，相当于延时刷新，会闪一下
![image](https://github.com/SmileZXLee/uni-z-paging/assets/92135677/7c7fdd77-f942-437a-8d11-af924a11ba4f)
因为使用watch监听父组件onshow传递的isRefresh，切换到其他页面再切换回来时会刷新，created中初始化数据onRefresh，去掉onRefresh也还是空白
![image](https://github.com/SmileZXLee/uni-z-paging/assets/92135677/d0a8cad5-ebc8-4e73-84e6-604d5039dcca)

主要涉及到的代码
```
watch: {
    isRefresh: {
      handler: function () {
        console.log("message on search ");
        this.onRefresh();
      },
    },
  },
```

```
created() {
    this.onRefresh();
  },
```

``` 
onRefresh() {
      // 清空列表数据
      this.list = [];
      this.$refs.paging.clear();
      this.$refs.paging.updatePageScrollTopHeight();
      // 重新加载数据
      this.loadingStatus = "more";
      this.onLoad(true);
    },
 ```

**Comment by CymuYae** [comment]
进入页面时自动调了reload()但是数据没有展示，再掉一次onRefresh也无济于事

**Comment by SmileZXLee** [comment]
试试demo是否有问题

**Comment by CymuYae** [comment]
> 试试demo是否有问题

解决了，貌似是watch的问题？去掉created，改成只在onHide调用onRefresh就没问题了，不知道什么原因导致的，进入页面只有默认的reload被调用了，并没有做其他操作
