### ISSUE TITLE
聊天记录模式加非固定模式时，键盘弹出列表也同步向上弹

### ISSUE THREAD

**Issue by yiluzhang** [SmileZXLee/uni-z-paging#109]
编译平台：HbuilderX 3.99
VUE版本：vue3
运行平台：APP
z-paging版本：2.7.3

**问题描述**
看板APP，聊天窗口在局部展示，并非底部。

**Comment by SmileZXLee** [comment]
v2.7.4支持设置使用聊天记录模式中键盘弹出时是否自动调整slot="bottom"高度，可以更新下哦
<img width="784" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/247237e5-b44a-4abd-a088-84780c7043b6">
