### ISSUE TITLE
有没有考虑过下拉刷新仅仅做刷新，不是分页的场景，例如商品详情页

### ISSUE THREAD

**Issue by 1093439315** [SmileZXLee/uni-z-paging#11]

**Comment by SmileZXLee** [comment]
支持的，设置`refresher-only`即可。可参见文档：[https://z-paging.com/api/props/refresher.html](https://z-paging.com/api/props/refresher.html)。或下载demo，`index.vue`中就是类似用法。

**Comment by 1093439315** [comment]
好的，我试试，Thanks
