### ISSUE TITLE
启用了use-chat-record-mode模式 列表里的子项都倒过来了 

### ISSUE THREAD

**Issue by op89as** [SmileZXLee/uni-z-paging#112]
**编译平台**
使用HbuilderX还是npm方式编译出现的问题？（如：HbuilderX）
HbuilderX 3.99
**VUE版本**
在vue2还是vue3中出现的问题，是nvue还是vue？（如：vue2+nvue）
vue2+nvue
**运行平台**
在运行到哪个平台中出现的问题？（如：App、微信小程序、h5）
H5以及APP
**z-paging版本**
在哪个版本的z-paging中出现的问题？
2.5.9（这个版本一开始只有app里会出现且2024/1/30是正常的 1/31出现） 与 2.7.5(更新到该版本H5与App都出现)
**问题描述**
![Snipaste_2024-01-31_15-37-14](https://github.com/SmileZXLee/uni-z-paging/assets/66147663/0f92bb57-c8d5-4f12-9677-1c21a0ce104c)
自定义组件用xxx代替
`<z-paging use-chat-record-mode :auto="false" :refresher-enabled="false" :loading-more-enabled="false"
			bg-color="#f5f5f5" ref="paging" v-model="form" @query="queryList">
			<view slot="top" class="defect-records-head">
				xxx
				<view class="add-records">
					<view @click="addItem" class="add-records-btn">
						<text class="icon icon-add">{{ iconObj.add2 }}</text>
					</view>
					<text class="add-records-text">新增记录</text>
				</view>
			</view>
			<z-paging-cell v-for="(item, index) in form" :key="index" :cellStyle="{
					padding: '15px 15px 0 15px'
				}">
				<view class="records-box">
					xxx
					<view class="records-box-input">
						<text class="body-title">缺陷描述</text>
						<view class="">
							xxx
						</view>
					</view>
					<view class="records-box-input">
						<text class="body-title">缺陷等级</text>
						<view @click="openPicker(index)" class="">
							xxx
						</view>
					</view>
					<view class="records-box-input" style="flex-direction: row;">
						<text class="body-title">缺陷数量</text>
						<view class="step">
							xxx
						</view>
					</view>
					<view class="records-box-btn">
						xxx
					</view>
				</view>
			</z-paging-cell>
			<view slot="bottom" class="bottom-btn">
				xxx
			</view>
		</z-paging>`

**Comment by SmileZXLee** [comment]
<img width="1199" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/9bfcd6de-d21b-434a-8822-8b5c7f521b7f">
写法有变更，请下载最新demo并参照demo写法
