### ISSUE TITLE
App中虚拟列表使用子组件做为cell slot会丢失数据和样式

### ISSUE THREAD

**Issue by Z-Joker** [SmileZXLee/uni-z-paging#113]
**编译平台**
HbuilderX

**VUE版本**
vue2

**运行平台**
App

**z-paging版本**
2.7.5

**问题描述**
把示例中虚拟列表cell slot换成<virtual-list-test-cell>子组件之后，在App上数据加载到100行以上之后再往回滑动，会出现数据和样式丢失的情况。在子组件的生命周期中打印了props能取到值，但是显示就有问题。数据和样式都丢失了。

![Y90XO1M7NJA{Y2 $H7L1CBK](https://github.com/SmileZXLee/uni-z-paging/assets/23055069/5124fc0a-4f19-49a3-97a8-03a7bc4b3d77)

![Screenshot_2024-02-14-11-59-01-32](https://github.com/SmileZXLee/uni-z-paging/assets/23055069/1a543558-7863-4bd0-aac2-ed2808576a3f)

https://github.com/SmileZXLee/uni-z-paging/assets/23055069/997451d4-c393-49d9-aa9c-1fc4e7699edf

**Comment by toesbieya** [comment]
能问下咋解决的吗，我排查了下是uniapp问题，安卓下for循环插槽在数据变动的时候渲染异常，只能用非内置列表写法
