### ISSUE TITLE
z-paging-cell touchstart 无效

### ISSUE THREAD

**Issue by kosuke-zhang** [SmileZXLee/uni-z-paging#116]
HbuilderX/npm vue2 h5/app

<z-paging-cell @touchstart="touchstart"> 无效

<cell @touchstart="touchstart"> 有效

**Comment by SmileZXLee** [comment]
这个目前应该只能修改源码，在z-paging-cell中给view加@touchstart="touchstart"，然后把对应事件emit出来

**Comment by SmileZXLee** [comment]
感谢反馈，v2.7.7中将补充touchstart事件
