### ISSUE TITLE
我手动将第一页列表删除后，如何自动加载新的一页？

### ISSUE THREAD

**Issue by 2424004764** [SmileZXLee/uni-z-paging#118]
** 请描述您在使用期间遇到的疑问 **

我每页10条数据，这是我的第一页数据：
![image](https://github.com/SmileZXLee/uni-z-paging/assets/24261680/c65f575e-8fa3-450e-affb-a333d673c342)

此时我手动将列表数据都删除后组件内容显示“没有数据哦！”：
![image](https://github.com/SmileZXLee/uni-z-paging/assets/24261680/c29ebdd7-8a29-49b2-896c-7f2d70a07071)

这里能否删除完后自动加载一次数据呢？
这个功能是否可以通过现有配置实现？

我使用的版本为：v2.5.9 (2023-09-25)

**Comment by SmileZXLee** [comment]
可以通过调用z-paging的reload方法刷新列表数据
