### ISSUE TITLE
啥时候考虑出个vue3的版本

### ISSUE THREAD

**Issue by parahell1** [SmileZXLee/uni-z-paging#12]
现在支持vue3的下拉刷新上拉加载的组件太少了。
mescroll说是支持vue3，但是只能在options api下使用，这和不支持vue3也没区别。而且依赖onPageScroll、onReachBottom这几个页面的生命周期，封装成组件也需要在页面支持这几个生命周期，又回到options api了。
我现在解决方案是用scroll-view，但是onPullDownRefresh无法一起用。
总之，还是需要一个完美支持vue3+ts的上拉下拉组件。这个市场目前还是空白，希望大佬能考虑下

**Comment by SmileZXLee** [comment]
感谢建议，近期会支持vue3。

**Comment by SmileZXLee** [comment]
已支持vue3
