### ISSUE TITLE
滚动到底部有延迟

### ISSUE THREAD

**Issue by yobbo-wang** [SmileZXLee/uni-z-paging#121]
2.
this._scrollToBottom(false);
u.delay(() => {
	this._scrollToBottom(false);
	u.delay(() => {
		this._scrollToBottom(false);
	}, 50)
}, 50)
时间太短没渲染完成会失败

**Comment by SmileZXLee** [comment]
如果cell是动态增高的，比如通过图片撑高，需要等图片加载结束再滚动到底部，因为这时候高度才确定
