### ISSUE TITLE
错误信息

### ISSUE THREAD

**Issue by lj1026203182** [SmileZXLee/uni-z-paging#122]
**请详细描述您的需求或想法**
由于错误原因各种各样,希望paging.value.complete(false)的时候可以多加一个参数,使得改变默认的empty-view-error-text. 比如 paging.value.complete(false,'错误的参数').  

当然可以动态设置empty-view-error-text,可就是想通过js调用,省去了维护empty-view-error-text字段的逻辑

**Comment by SmileZXLee** [comment]
![image](https://github.com/SmileZXLee/uni-z-paging/assets/29226317/84f00b18-0d8b-4f5a-afad-a6a3821db6f3)
支持的，可以使用`completeByError `方法
