### ISSUE TITLE
聊天记录模式，当数据不能占满一页时，数据显示异常

### ISSUE THREAD

**Issue by StevenMinrun** [SmileZXLee/uni-z-paging#125]
请教各位大佬，怎么设置让它从上往下显示呢？
![微信图片_20240424153621](https://github.com/SmileZXLee/uni-z-paging/assets/49259859/2fb41148-c323-48ae-a2ca-109c009fb6f5)

**Comment by SmileZXLee** [comment]
默认是从顶部显示的，更新到最新版本试下

**Comment by StevenMinrun** [comment]
> 默认是从顶部显示的，更新到最新版本试下

我的版本是2.7.6，应该不是版本的问题吧

**Comment by SmileZXLee** [comment]
试试demo有无问题
