### ISSUE TITLE
【严重致命BUG】源码的Vue文件里面的wxsPropType和isIosAndH5变量没有默认值导致APP运行不了

### ISSUE THREAD

**Issue by 1014156094** [SmileZXLee/uni-z-paging#129]
**编译平台**
使用HbuilderX还是npm方式编译出现的问题？（如：HbuilderX）
4.15

**VUE版本**
在vue2还是vue3中出现的问题，是nvue还是vue？（如：vue2+nvue）
vue3

**运行平台**
在运行到哪个平台中出现的问题？（如：App、微信小程序、h5）
APP

**z-paging版本**
在哪个版本的z-paging中出现的问题？
2.7.8（2024-05-09）

**问题描述**
请详细描述问题，最好说明复现步骤，尽可能附上代码或截图
![image](https://github.com/SmileZXLee/uni-z-paging/assets/16074662/1d538a1b-df15-412d-a7f6-4fbaa7ccbbbf)

![image](https://github.com/SmileZXLee/uni-z-paging/assets/16074662/d8e8c266-1c6e-4797-98e9-cb3c3bfa35d8)

**Comment by 1014156094** [comment]
uni-app更新到4010220240409001之后正常了

**Comment by SmileZXLee** [comment]
OK
