### ISSUE TITLE
钉钉小程序下报错

### ISSUE THREAD

**Issue by lsj3210** [SmileZXLee/uni-z-paging#13]
[Vue warn]: Error in callback for immediate watcher "nIsFirstPageAndNoMore": "TypeError: Cannot read property 'props' of undefined"
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'props' of undefined"

**Comment by lsj3210** [comment]
![image](https://user-images.githubusercontent.com/12181169/150961278-d6e260e4-9c54-4178-8afb-8de90476a082.png)

**Comment by SmileZXLee** [comment]
未发现此问题，请更新编译器或重启项目重试一下。
