### ISSUE TITLE
【uniapp小程序】【安卓】列表在上划下拉刷新三四次列表后，页面下拉刷新功能无法使用

### ISSUE THREAD

**Issue by ke-gui** [SmileZXLee/uni-z-paging#131]
**编译平台**
HbuilderX

**VUE版本**
vue2

**运行平台**
微信小程序

**z-paging版本**
2.7.4

**问题描述**
请详细描述问题，最好说明复现步骤，尽可能附上代码或截图

https://github.com/SmileZXLee/uni-z-paging/assets/106938585/96da5fee-87d9-48e5-9c44-1d623fa9beae

**Comment by SmileZXLee** [comment]
更新一下最新版本试下

**Comment by SmileZXLee** [comment]
<img width="1040" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/60cad29a-8aae-44c3-9f01-bb9f4b462076">

**Comment by ke-gui** [comment]
更新后没问题了，感谢
