### ISSUE TITLE
加载到最后一条数据不显示没有更多了

### ISSUE THREAD

**Issue by 601544679** [SmileZXLee/uni-z-paging#133]
**编译平台**
vscode

**VUE版本**
vite5.2.11 vue3.4.21

**运行平台**
微信小程序

**z-paging版本**
z-paging2.7.8

**问题描述**
npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project创建的项目，把"@dcloudio/xx": "3.0.0-4000820240401001",更新到3.0.0-4000820240401001往后的版本vite版本和vue3版本要更新(vite5.2.11 vue3.4.21),一直往下加载数据，加载到最后一条数据，不显示没有更多了，如果一页能加载完，就会显示没有更多了，版本降回"@dcloudio/xx": "3.0.0-4000820240401001"(vite 4.5.3, vue 3.3.11)就没有此异常

**Comment by SmileZXLee** [comment]
更新到2.7.9后再次尝试

**Comment by 601544679** [comment]
> 更新到2.7.9后再次尝试

完美解决
