### ISSUE TITLE
使用resetTotalData方法更新页面数据显示问题

### ISSUE THREAD

**Issue by libian2540926286** [SmileZXLee/uni-z-paging#135]
**编译平台**
使用HbuilderX还是npm方式编译出现的问题？（如：HbuilderX）

**VUE版本**
vue3

**运行平台**
h5

**z-paging版本**
v2.7.6

**问题描述**
在使用后端翻页场景下，在翻页过程实现全选逻辑，使用resetTotalData方法更新页面选中状态时，resetTotalData中装了40条数据，但是渲染出来数据的id="zp-id-undefined"或者id="zp-id-43"等，点击获取到的rowIndex大于数据条数，麻烦大佬帮忙看下。
或者帮忙提供下更合理的更新、插入、删除数据的案例demo，谢谢！。
![image](https://github.com/SmileZXLee/uni-z-paging/assets/33245991/67bfb165-5a29-487b-aa55-6ae18101beb3)

**Comment by SmileZXLee** [comment]
如果实现全选逻辑，只需要修改所有item的选中状态即可。不要使用resetTotalData去进行重新赋值。如果是vue2可以使用this.$set进行响应式赋值

**Comment by libian2540926286** [comment]
谢谢答复，这种修改数据item的方法可以实现数据的更新操作，那对于插行和删行操作不使用resetTotalData的话应该如何操作呢？

**Comment by SmileZXLee** [comment]
> 谢谢答复，这种修改数据item的方法可以实现数据的更新操作，那对于插行和删行操作不使用resetTotalData的话应该如何操作呢？

this.dataList.push, this.dataList.splice。如果是不固定高度的虚拟列表，还需要更新缓存的虚拟列表高度，具体文档中有对应方法

**Comment by SmileZXLee** [comment]
> 谢谢答复，这种修改数据item的方法可以实现数据的更新操作，那对于插行和删行操作不使用resetTotalData的话应该如何操作呢？

this.dataList.push, this.dataList.splice。如果是不固定高度的虚拟列表，还需要更新缓存的虚拟列表高度，具体文档中有对应方法

**Comment by libian2540926286** [comment]
你好，我按照下面的方法插行操作，第一次页面20条数据，插行1条之后paingList是21条数据，下拉翻页返回20条数据之后paingList成了42条数据了，这种问题该如何解决麻烦帮忙看下吧？
![image](https://github.com/SmileZXLee/uni-z-paging/assets/33245991/6430dc06-1466-49ae-8d91-c82da4bf5b25)
![image](https://github.com/SmileZXLee/uni-z-paging/assets/33245991/b2d70004-603a-4bb9-a0f9-c74132d797b0)
![image](https://github.com/SmileZXLee/uni-z-paging/assets/33245991/1c7829e1-d393-4495-993c-240ef8c788e1)

**Comment by SmileZXLee** [comment]
在demo基础上修改并提供最小可复现demo

**Comment by libian2540926286** [comment]
写了个简单的demo没有问题，问题已解决，感谢回复！！！
