### ISSUE TITLE
使用use-chat-record-mode后，安卓9及一下的不兼容，滑不动列表

### ISSUE THREAD

**Issue by FlyLi1024** [SmileZXLee/uni-z-paging#136]
**编译平台**
HbuilderX

**VUE版本**
vue2

**运行平台**
App

**z-paging版本**
2.7.9

**问题描述**
使用use-chat-record-mode后，安卓9及一下的不兼容，滑不动列表

**Comment by FlyLi1024** [comment]
试了demo也是有这个问题

**Comment by SmileZXLee** [comment]
<img width="1218" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/13f5607c-84f9-40d4-8043-510b82c09820">
