### ISSUE TITLE
将所有数据再进行操作，要如何写呢

### ISSUE THREAD

**Issue by happy2277** [SmileZXLee/uni-z-paging#140]
** 请描述您在使用期间遇到的疑问 **
请求后的数据因状态问题，需要重新排序，这个要怎么写呢？

**Comment by jerrytang67** [comment]
paging.reload()

**Comment by happy2277** [comment]
重载数据没用，我的情况是分页获取到的所有数据，最后还得再操作重排一次

> paging.reload()

**Comment by SmileZXLee** [comment]
已在群中解答，可自行处理分页数据
