### ISSUE TITLE
为什么会覆盖全屏，有没有什么方法规避，让其显示再一个容器中

### ISSUE THREAD

**Issue by nanfb** [SmileZXLee/uni-z-paging#141]
我不理解为什么这个组件默认会占满整个屏幕，我感觉这并不合理，虽然组件内部提供了一些位置的插槽，但我觉得这是一种过渡设计，
考虑这样一种场景:现在有个页面，需要将list列表组件更换成这个组件，这样会导致你必须将这个页面的其他元素也一一修改，这很不友好，

**Comment by SmileZXLee** [comment]
默认设计是铺满全屏的，您也可以通过`:fixed="false"`来取消铺满全屏，从而把z-paging当作类似普通scroll-view使用，此时需要确保有确定的高度。
![image](https://github.com/SmileZXLee/uni-z-paging/assets/29226317/01a83022-b39f-48de-a27e-57a44fe84827)

**Comment by nanfb** [comment]
> 默认设计是铺满全屏的，您也可以通过`:fixed="false"`来取消铺满全屏，从而把z-paging当作类似普通scroll-view使用，此时需要确保有确定的高度。 ![image](https://private-user-images.githubusercontent.com/29226317/339686034-01a83022-b39f-48de-a27e-57a44fe84827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTcxNDAsIm5iZiI6MTcxODM1Njg0MCwicGF0aCI6Ii8yOTIyNjMxNy8zMzk2ODYwMzQtMDFhODMwMjItYjM5Zi00OGRlLWEyN2UtNTdhNDRmZTg0ODI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjQwOWMwOGY0ZTg1NmY0NzQwYjYzZjBmMmEzZTg4OTgxMTEwNDVlNjE0MzE3YTczMzY0ZDcxOTIxYjM1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXI1wKwutVzXJFJBD4SjAScasWU7Fho9aF5aIJte4j8)

最后一个页面滚动使用的是uniapp自带的还是自己的

**Comment by SmileZXLee** [comment]
> > 默认设计是铺满全屏的，您也可以通过`:fixed="false"`来取消铺满全屏，从而把z-paging当作类似普通scroll-view使用，此时需要确保有确定的高度。 ![image](https://private-user-images.githubusercontent.com/29226317/339686034-01a83022-b39f-48de-a27e-57a44fe84827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTcxNDAsIm5iZiI6MTcxODM1Njg0MCwicGF0aCI6Ii8yOTIyNjMxNy8zMzk2ODYwMzQtMDFhODMwMjItYjM5Zi00OGRlLWEyN2UtNTdhNDRmZTg0ODI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjQwOWMwOGY0ZTg1NmY0NzQwYjYzZjBmMmEzZTg4OTgxMTEwNDVlNjE0MzE3YTczMzY0ZDcxOTIxYjM1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXI1wKwutVzXJFJBD4SjAScasWU7Fho9aF5aIJte4j8)
> 
> 最后一个页面滚动使用的是uniapp自带的还是自己的

使用的是uniapp自带的页面滚动

**Comment by nanfb** [comment]
> > > 默认设计是铺满全屏的，您也可以通过`:fixed="false"`来取消铺满全屏，从而把z-paging当作类似普通scroll-view使用，此时需要确保有确定的高度。 ![image](https://private-user-images.githubusercontent.com/29226317/339686034-01a83022-b39f-48de-a27e-57a44fe84827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTcxNDAsIm5iZiI6MTcxODM1Njg0MCwicGF0aCI6Ii8yOTIyNjMxNy8zMzk2ODYwMzQtMDFhODMwMjItYjM5Zi00OGRlLWEyN2UtNTdhNDRmZTg0ODI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjQwOWMwOGY0ZTg1NmY0NzQwYjYzZjBmMmEzZTg4OTgxMTEwNDVlNjE0MzE3YTczMzY0ZDcxOTIxYjM1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXI1wKwutVzXJFJBD4SjAScasWU7Fho9aF5aIJte4j8)
> > 
> > 
> > 最后一个页面滚动使用的是uniapp自带的还是自己的
> 
> 使用的是uniapp自带的页面滚动

那加载icon也是从整个页面开始的吗，这样就不能使用组件内的自定义了吧

**Comment by nanfb** [comment]
> > > > 默认设计是铺满全屏的，您也可以通过`:fixed="false"`来取消铺满全屏，从而把z-paging当作类似普通scroll-view使用，此时需要确保有确定的高度。 ![image](https://private-user-images.githubusercontent.com/29226317/339686034-01a83022-b39f-48de-a27e-57a44fe84827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTcxNDAsIm5iZiI6MTcxODM1Njg0MCwicGF0aCI6Ii8yOTIyNjMxNy8zMzk2ODYwMzQtMDFhODMwMjItYjM5Zi00OGRlLWEyN2UtNTdhNDRmZTg0ODI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjQwOWMwOGY0ZTg1NmY0NzQwYjYzZjBmMmEzZTg4OTgxMTEwNDVlNjE0MzE3YTczMzY0ZDcxOTIxYjM1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXI1wKwutVzXJFJBD4SjAScasWU7Fho9aF5aIJte4j8)
> > > 
> > > 
> > > 最后一个页面滚动使用的是uniapp自带的还是自己的
> > 
> > 
> > 使用的是uniapp自带的页面滚动
> 
> 那加载icon也是从整个页面开始的吗，这样就不能使用组件内的自定义了吧，我想的是从view下面开始

**Comment by SmileZXLee** [comment]
> > > > 默认设计是铺满全屏的，您也可以通过`:fixed="false"`来取消铺满全屏，从而把z-paging当作类似普通scroll-view使用，此时需要确保有确定的高度。 ![image](https://private-user-images.githubusercontent.com/29226317/339686034-01a83022-b39f-48de-a27e-57a44fe84827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTcxNDAsIm5iZiI6MTcxODM1Njg0MCwicGF0aCI6Ii8yOTIyNjMxNy8zMzk2ODYwMzQtMDFhODMwMjItYjM5Zi00OGRlLWEyN2UtNTdhNDRmZTg0ODI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjQwOWMwOGY0ZTg1NmY0NzQwYjYzZjBmMmEzZTg4OTgxMTEwNDVlNjE0MzE3YTczMzY0ZDcxOTIxYjM1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXI1wKwutVzXJFJBD4SjAScasWU7Fho9aF5aIJte4j8)
> > > 
> > > 
> > > 最后一个页面滚动使用的是uniapp自带的还是自己的
> > 
> > 
> > 使用的是uniapp自带的页面滚动
> 
> 那加载icon也是从整个页面开始的吗，这样就不能使用组件内的自定义了吧

从组件的位置开始的，不是从页面开始

**Comment by SmileZXLee** [comment]
当然不能用pages.json的下拉刷新，这是系统的，自然从页面顶部开始。你要用z-paging自带的下拉刷新，才是从z-paging位置开始

**Comment by nanfb** [comment]
> 当然不能用pages.json的下拉刷新，这是系统的，自然从页面顶部开始。你要用z-paging自带的下拉刷新，才是从z-paging位置开始

但是我使用的是use-page-scroll，你说他是监听页面的，所以是不需要开启吗？还是我使用的姿势有问题

**Comment by SmileZXLee** [comment]
不需要在pages.json中开始页面下拉刷新，但是你要支持z-paging的下拉刷新，必须在queryList中调用complete，不然没办法下拉刷新。具体看页面滚动的demo，写得很详细的了。

**Comment by nanfb** [comment]
> 不需要在pages.json中开始页面下拉刷新，但是你要支持z-paging的下拉刷新，必须在queryList中调用complete，不然没办法下拉刷新。具体看页面滚动的demo，写得很详细的了。

我看了很多demo，跟我情况都不太一样，很奇怪，我不知道为什么设计的这么复杂，我理解的是只要内部只要有数据就会开启下拉，我如果作为一个内部组件使用，全都变了，我觉得不应该设计成这样

**Comment by SmileZXLee** [comment]
你提供的信息不足，无法解决。你如果要只使用下拉刷新，就设置`refresher-only`，就可以只用下拉刷新。

**Comment by nanfb** [comment]
> 置

我重写了我的组件，我还是觉得组件内部自动进行分页处理不太好。。
