### ISSUE TITLE
uniapp vue3 在编译成支付宝小程序中，所有卡槽失效，微信小程序中正常是什么原因

### ISSUE THREAD

**Issue by SunYuanOnly** [SmileZXLee/uni-z-paging#143]
** 请描述您在使用期间遇到的疑问 **

如下图使用了top卡槽。

1. 支付宝小程序截图

![image](https://github.com/SmileZXLee/uni-z-paging/assets/16498201/9ec1281d-68c3-44ff-ab36-5f7187638dd4)
 2. 微信小程序截图

![image](https://github.com/SmileZXLee/uni-z-paging/assets/16498201/b1e920d7-c9b5-4990-a37a-401e6afd26cf)

 3. 代码如下：
 
![image](https://github.com/SmileZXLee/uni-z-paging/assets/16498201/4301d903-3aed-4bbb-944a-a86039cb0ceb)

![image](https://github.com/SmileZXLee/uni-z-paging/assets/16498201/5a6841c4-f669-4656-8cf2-ac06d144ed70)

_pnpm安装easycom模式_

**Comment by SmileZXLee** [comment]
你好，我使用demo运行到支付宝小程序未发现此问题。请使用此项目的vue3demo运行到支付宝小程序后尝试下

**Comment by SunYuanOnly** [comment]
demo用HbuilderX导入编译成小程序没问题。不知道我的为啥在支付宝里无法获取到slot信息....

**Comment by SmileZXLee** [comment]
麻烦提供一个简单的可复现的示例，我排查下原因，感谢

**Comment by SunYuanOnly** [comment]
[Uploading test.zip…]()



> 麻烦提供一个简单的可复现的示例，我排查下原因，感谢

**Comment by SunYuanOnly** [comment]
> 麻烦提供一个简单的可复现的示例，我排查下原因，感谢

[test.zip](https://github.com/user-attachments/files/15983082/test.zip)

**Comment by SunYuanOnly** [comment]
> 麻烦提供一个简单的可复现的示例，我排查下原因，感谢
![image](https://github.com/SmileZXLee/uni-z-paging/assets/16498201/608a6eba-4030-4edf-951c-f2439dc2b2c6)
好像是它版本的bug。升级版本后就可以了。
