### ISSUE TITLE
调用refresh时候，page自动变1了。

### ISSUE THREAD

**Issue by sdaiber** [SmileZXLee/uni-z-paging#145]
请问有refresh的demo吗？是我哪里配置的不对吗？

**Comment by SmileZXLee** [comment]
设计就是这样的，refresh就是用来刷新当前已加载页面的所有数据，假设你当前滚动到第五页，此时想要刷新所有已加载的数据的话，pageNo应当等于1，pageSize=50，这样才是刷新前面5页数据，如果你调用refresh后继续滚动到底部，pageNo会从6开始，而不是从1开始，因此这样是合理的，也是设计所需

**Comment by sdaiber** [comment]
原来如此，谢谢大佬

**Comment by SmileZXLee** [comment]
不客气
