### ISSUE TITLE
聊天记录模式时，当有top插槽时，滚动位置错误

### ISSUE THREAD

**Issue by qzsiniong** [SmileZXLee/uni-z-paging#15]
https://github.com/SmileZXLee/uni-z-paging/blob/aa00316d19127db69444097d60d714921c81d7b8/z-paging/uni_modules/z-paging/components/z-paging/js/z-paging-main.js#L1898

这里的`offset` 30是`.zp-chat-record-loading-container`的高度，少了top插槽高度

**Comment by qzsiniong** [comment]
这个`30`也不能写死。自定义`slot="chatLoading"`时高度不一定是`30`哦

**Comment by SmileZXLee** [comment]
30是写死的，这30只是偏移一点，让新加载的数据露出来一点，否则看不到上面新的
