### ISSUE TITLE
全屏Loading Slot 当auto-show-system-loading=false, auto-hide-loading-after-first-loaded=false时, 第一次调用reload()方法不展示全屏Loading

### ISSUE THREAD

**Issue by Ilymfa** [SmileZXLee/uni-z-paging#156]
**编译平台**
HbuilderX、npm都存在

**VUE版本**
vue3

**运行平台**
h5

**z-paging版本**
2.7.11

**问题描述**
配置 全屏Loading Slot,并且auto-show-system-loading=false, auto-hide-loading-after-first-loaded=false时,  第一次调用reload(true)方法不展示全屏Loading, 第二次及以后正常展示
![WX20240821-161620](https://github.com/user-attachments/assets/65840655-50de-43b3-8ceb-f002e1848d0f)

**Comment by Ilymfa** [comment]
![Uploading WX20240821-161620.png…]()

**Comment by SmileZXLee** [comment]
感谢反馈，已解决，请下载github中最新的z-paging替换
