### ISSUE TITLE
reload时，应该显示solt="loading"

### ISSUE THREAD

**Issue by qzsiniong** [SmileZXLee/uni-z-paging#16]
https://github.com/SmileZXLee/uni-z-paging/blob/5ca7fa2dc8fb70980aeb7046894f6b7bcff9e374/z-paging/uni_modules/z-paging/components/z-paging/js/z-paging-main.js#L1252

`autoHideLoadingAfterFirstLoaded`设置为`true`，`reload`时，`solt="loading"`不显示

按我的理解，`autoHideLoadingAfterFirstLoaded`意思是，加载第一页时显示loading，加载第2/3...页时隐藏loading

但是现在只有第一次加载第一页时才显示，reload加载第一页时不显示了

是不是应该在reload时将`this.pagingLoaded`设置为false

**Comment by SmileZXLee** [comment]
感谢反馈，将在`2.1.7`版本中修复此问题。

**Comment by wojide0301** [comment]
2.8.6 版本h5又复现此问题
