### ISSUE TITLE
当作为scroll-view去使用时，通过page-style设置了高度，设置了scroll-x，但还是没办法横向滚动，有什么具体的例子可以参考一下吗？

### ISSUE THREAD

**Issue by weiqiyue** [SmileZXLee/uni-z-paging#162]
当作为scroll-view去使用时，通过page-style设置了高度，设置了scroll-x，但还是没办法横向滚动，有什么具体的例子可以参考一下吗？

**Comment by SmileZXLee** [comment]
需要给你内容容器设置超出屏幕宽度，才可以横向滚动，例如设置宽度为1000px

**Comment by weiqiyue** [comment]
> 需要给你内容容器设置超出屏幕宽度，才可以横向滚动，例如设置宽度为1000px

🙇‍，试了一下，是可以的，3Q
