### ISSUE TITLE
关于下拉刷新触发的问题

### ISSUE THREAD

**Issue by MangMax** [SmileZXLee/uni-z-paging#167]
vue3中，开启页面滚动和仅下拉刷新，使用竖向的flex布局，父容器使用flex-1占满中间的高度，列表在任何位置都会触发下拉刷新，已经根据文档使用hooks

**Comment by SmileZXLee** [comment]
试试demo是否有问题呢，未能复现

**Comment by c-sopoo** [comment]
> vue3中，开启页面滚动和仅下拉刷新，使用竖向的flex布局，父容器使用flex-1占满中间的高度，列表在任何位置都会触发下拉刷新，已经根据文档使用hooks

vue3微信小程序同样的问题，发现问题出在hooks内的onPageScroll没有正常调用，需要在页面引入，就是文档写的那样
![image](https://github.com/user-attachments/assets/fb4705c6-68c9-4810-9467-299f56e760ee)
