### ISSUE TITLE
空数据时，默认插槽view的padding以及开启use-safe-area-placeholder时底部安全区的占位view影响了empty view的垂直居中

### ISSUE THREAD

**Issue by zybzzc** [SmileZXLee/uni-z-paging#170]
我现在的结局方案是根据 lis t数据动态隐藏它们：
```vue
<template>
  <view class="h-screen w-screen overflow-hidden">
    <z-paging
      ref="paging"
      v-model="dataList"
      safe-area-inset-bottom
      :use-safe-area-placeholder="dataList.length > 0"
      @query="queryList"
    >
      <template #top>
        <Navbar title="我的收藏" :delta="1" />
      </template>
      <view v-show="dataList.length > 0" class="p-4">
        <AttractionList :items="dataList" />
      </view>
      <template #empty>
        <Empty type="box" description="这里空的哦～" />
      </template>
    </z-paging>
  </view>
</template>
```

我在想是否可以 z-paging 内部直接处理

**Comment by SmileZXLee** [comment]
因为`use-safe-area-placeholder`是将底部安全区域调整为占位区域，因此空数据图整体位置会偏下。这是正常的，你按照现在的`:use-safe-area-placeholder="dataList.length > 0"`处理即可。如果这个在组件内部处理是可以的，但是有些情况数据为空也需要底部的占位空间：例如不使用分页自己填充数据的情况，所以组件内部判断dataList为空就关闭`use-safe-area-placeholder`是不合理的。`:use-safe-area-placeholder="dataList.length > 0"`符合你的需求并且不会影响其他的需求，是最佳做法。

**Comment by ByteRax** [comment]
感谢分享，遇到同样的问题safe-area 在空数据的上面了。。。。

<img width="412" height="869" alt="Image" src="https://github.com/user-attachments/assets/430e9e79-4f76-4633-a5fa-a05fe4b21e54" />

**Comment by SmileZXLee** [comment]
> 感谢分享，遇到同样的问题safe-area 在空数据的上面了。。。。
> 
> <img alt="Image" width="412" height="869" src="https://private-user-images.githubusercontent.com/5227840/584266930-430e9e79-4f76-4633-a5fa-a05fe4b21e54.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzc0MzAwMzUsIm5iZiI6MTc3NzQyOTczNSwicGF0aCI6Ii81MjI3ODQwLzU4NDI2NjkzMC00MzBlOWU3OS00Zjc2LTQ2MzMtYTVmYS1hMDVmZTRiMjFlNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MjlUMDIyODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UxNGFjNjc1MDE0ZmU4ZjU3NzFkM2QzZjQyNTNlNzIzZGQ3MGQ3ZTQ4ZGNlZGEyY2NmYjU5OTA5NjNjNGU5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.d43prBxNGkns-ZEizAoH631GuEBCjvmhzjY4Au0p3rk">

你这个空数据图，是通过slot=empty插入的吗？
