### ISSUE TITLE
聊天记录模式，H5生成的dom元素有2个一样的uni-scroll-view

### ISSUE THREAD

**Issue by xiaofei3062** [SmileZXLee/uni-z-paging#171]
![image](https://github.com/user-attachments/assets/2d36eded-a4ef-45b6-a9e0-1149001eeb40)
聊天记录模式，H5生成的dom元素有2个一样的uni-scroll-view
并且第二个uni-scroll-view的overflow样式为hidden auto
希望后面版本可以优化下

**Comment by SmileZXLee** [comment]
目前有什么影响吗？这个样式是scroll-view内部的。实际上只有一个scroll-view。

**Comment by xiaofei3062** [comment]
没有，原来是uni的问题，没事了

**Comment by SmileZXLee** [comment]
> 没有，原来是uni的问题，没事了

也不算问题吧，只是包了两个view，class一样，这个在实践中很常见，不影响正常使用即可。
