### ISSUE TITLE
z-paging 下拉模式，pageNo 无法自动更新

### ISSUE THREAD

**Issue by aimerthyr** [SmileZXLee/uni-z-paging#176]
用官网的案例就可以复现
<img width="881" alt="1" src="https://github.com/user-attachments/assets/80b2f2ee-c5a9-4a2d-b47c-13fbaec11969">

<img width="779" alt="2" src="https://github.com/user-attachments/assets/890d29ec-60eb-4442-861d-4c0e4d1b761f">

我在下拉刷新的时候，pageNo一直都是 1，希望是会自动递增

**Comment by SmileZXLee** [comment]
如果希望下拉刷新pageNo递增，可以自行处理pageNo，也就是在data中定义一个pageNo，然后在下拉刷新的时候把它+1

**Comment by aimerthyr** [comment]
> 如果希望下拉刷新pageNo递增，可以自行处理pageNo，也就是在data中定义一个pageNo，然后在下拉刷新的时候把它+1

好的，明白了
