### ISSUE TITLE
refresh时，nomore错误

### ISSUE THREAD

**Issue by qzsiniong** [SmileZXLee/uni-z-paging#18]
总共25条数据，每页10条，共3页
加载第2页后，调用`refresh`，此时显示`没有更多`，不能加载第3页了

[pages/debug/3-04-nomore-wrong-after-refresh.vue](https://github.com/qzsiniong/z-paging-demo/blob/a17abc4a20a591d96363615618550536c95a6d66/pages/debug/3-04-nomore-wrong-after-refresh.vue)

**Comment by SmileZXLee** [comment]
经检查无此问题，是测试数据不正确导致，请换成真实接口测试。

**Comment by hblz** [comment]
我也遇到过这个问题，数据是接口真实数据。场景应该是总共20+条数据到40+数据左右，目前我是39条的总共数据 会有这个情况。

**Comment by SmileZXLee** [comment]
> 我也遇到过这个问题，数据是接口真实数据。场景应该是总共20+条数据到40+数据左右，目前我是39条的总共数据 会有这个情况。

加群，提供录屏&可复现的demo

**Comment by hblz** [comment]
加了 等待同意
