### ISSUE TITLE
当前数据为空时，下拉刷新能否保留数据为空展示

### ISSUE THREAD

**Issue by yinfoyuan** [SmileZXLee/uni-z-paging#2]

**Comment by SmileZXLee** [comment]
`z-paging`提供了自动管理空数据图功能，当数据为空时，会自动显示空数据view。loading是用于展示”加载中...“的状态，数据为空时代表加载结束，不宜保留loading。建议采用空数据图来体现数据为空的状态，同时z-paging也支持自定义空数据图的，可以根据具体需求进行自定义。

**Comment by yinfoyuan** [comment]
不要意思我描述出错了，数据为空时下拉刷新能否保留 ，现在的效果会是  如果再次刷新 还是空  会闪烁

**Comment by SmileZXLee** [comment]
你好，可以更新最新版本，并且设置`auto-hide-empty-view-when-loading`为false即可。
