### ISSUE TITLE
2.2.0 版本，下拉刷新提示文字如何隐藏？

### ISSUE THREAD

**Issue by hdszy** [SmileZXLee/uni-z-paging#20]
![7T(LBW1X QFFAIEBP`0VXG4](https://user-images.githubusercontent.com/22936196/160748086-d474ab44-caa3-42d0-aca8-dbb94f922edb.png)
如图示，数据加载完毕后，下拉刷新提示文字跑到上边去了，没有办法隐藏掉。选项卡不是固定位置的，需要根据页面滚动而滚动。

**Comment by SmileZXLee** [comment]
固定在顶部的view，放在`slot="top"`内。

**Comment by hdszy** [comment]
使用 slot="top" 后，选项卡会出现最上边，而且会固定不动。
而我现在的 选项卡位置是在中间部分。  使用 微信小程序时，这个继续下拉刷新会隐藏。H5的不会隐藏
![image](https://user-images.githubusercontent.com/22936196/160763171-2c31b6ef-0ece-4bc9-a948-636b8011554d.png)

**Comment by hdszy** [comment]
这个是 微信小程序的截图，下拉提示会隐藏到选项卡下边。
![image](https://user-images.githubusercontent.com/22936196/160763529-c83e6742-009e-4003-a60b-e6f69dd68907.png)
H5 的截图，提示没有隐藏到选项卡下面。
![image](https://user-images.githubusercontent.com/22936196/160763619-b0b21e6b-f7cb-47ba-95a1-e846a4b28fa2.png)

**Comment by SmileZXLee** [comment]
选项卡设置提个背景色，灰色或者白色，因为选项卡是透明的所以可以看到下面的。
