### ISSUE TITLE
vue3 下拉刷新总是出现在左边 

### ISSUE THREAD

**Issue by anchao-lu** [SmileZXLee/uni-z-paging#21]
<img width="351" alt="截屏2022-04-04 20 34 31" src="https://user-images.githubusercontent.com/54097292/161544702-fc2a965f-b684-4265-9992-1d0040f98a84.png">
<img width="339" alt="截屏2022-04-04 20 34 50" src="https://user-images.githubusercontent.com/54097292/161544784-ce31f56a-a718-41e3-8041-e40feb379237.png">
是还没完全适配 vue3 吗？
当然这里使用自定义应该是没问题
但是 Vue3 还是一大堆问题的，有没有适配日程

**Comment by SmileZXLee** [comment]
经过测试未发现您所描述的问题，请确保HbuilderX和z-paging都已更新到最新版本。若问题依然存在，可以加群提供可复现的代码片段以便我排查，感谢。
