### ISSUE TITLE
refs mian 属性 无法找到问题

### ISSUE THREAD

**Issue by qingwuit** [SmileZXLee/uni-z-paging#22]
在使用vue3  H5 uniapp 编译的时候出现报错 
``
Cannot set property 'style' of undefined
``

组件加了  `use-page-scroll:true` 配置

#### line 82
``
this.$nextTick(()=>{
      this.$refs['zp-scroll-view'].$refs.main.style = {};
})
``

#### 我暂时本地改成了,
``
if(this.$refs['zp-scroll-view'].$refs.main) this.$refs['zp-scroll-view'].$refs.main.style = {};
``

**Comment by SmileZXLee** [comment]
感谢反馈，此问题已在`2.2.1`中修复。
