### ISSUE TITLE
使用css 反转变换暗黑模式时出现问题

### ISSUE THREAD

**Issue by Xiaotian0617** [SmileZXLee/uni-z-paging#28]
当我正常使用 z-paging时，无任何问题，当我在z-paging的外层增加一层

`<view :class="isDark?'dark-mode':''"></view>`

而dark-mode的定义为:

`
.dark-mode{
	filter:invert(1) hue-rotate(180deg);
}
`

此时，列表会直接消失，无法看到，请问该如何解决

**Comment by Xiaotian0617** [comment]
使用版本为 uni 市场最新版

**Comment by SmileZXLee** [comment]
父view设置`filter:invert(1) hue-rotate(180deg); `会导致子view的fixed布局失效，可参考[https://drafts.fxtf.org/filter-effects/#FilterProperty](https://drafts.fxtf.org/filter-effects/#FilterProperty)。  
解决方案：修改为在`z-paging`标签上设置filter:`<z-paging :paging-style="{filter:'invert(1)  hue-rotate(180deg)'}">`

**Comment by Xiaotian0617** [comment]
好的，谢谢
