### ISSUE TITLE
当页面中存在picker组件时，下拉picker组件会引起页面的下拉刷新

### ISSUE THREAD

**Issue by 1093439315** [SmileZXLee/uni-z-paging#30]
当页面中存在picker组件时，下拉picker组件会引起页面的下拉刷新，如何解决，盼回复！

**Comment by SmileZXLee** [comment]
你应该禁止下拉picker的的touchmove事件，`@touchmove.prevent`

**Comment by 1093439315** [comment]
感谢解答，试过了不好使，我在页面取消了zpaging，貌似只能这么干
