### ISSUE TITLE
聊天记录模式 底部输入弹起会把 top插槽里的内容顶出屏幕外

### ISSUE THREAD

**Issue by fe-room** [SmileZXLee/uni-z-paging#32]

**Comment by fe-room** [comment]
![35881660198962_ pic](https://user-images.githubusercontent.com/33181817/184075400-ce1ad319-28d4-4033-b638-26b561fd4e3b.jpg)
![35891660198980_ pic](https://user-images.githubusercontent.com/33181817/184075419-52c38d1c-2ec5-4795-9e10-bdbee1adbc7e.jpg)

**Comment by fe-room** [comment]
![35881660198962_ pic](https://user-images.githubusercontent.com/33181817/184075566-dc988594-838f-4f9a-9000-946b47ab1a97.jpg)
![35891660198980_ pic](https://user-images.githubusercontent.com/33181817/184075645-293d02ad-76a7-4c28-8b0a-f8c67a61e01c.jpg)

**Comment by SmileZXLee** [comment]
这个为系统行为，z-paging无法干预，建议使用系统导航栏。或是设置 input 的`adjust-position`属性，禁止上推页面。

**Comment by fe-room** [comment]
> 这个为系统行为，z-paging无法干预，建议使用系统导航栏。或是设置 input 的`adjust-position`属性，禁止上推页面。

好的，还有个问题是nvue 的情况下当没有聊天记录的时候 top插槽里的内容也无法正常显示

**Comment by SmileZXLee** [comment]
> > 这个为系统行为，z-paging无法干预，建议使用系统导航栏。或是设置 input 的`adjust-position`属性，禁止上推页面。
> 
> 好的，还有个问题是nvue 的情况下当没有聊天记录的时候 top插槽里的内容也无法正常显示

经过测试没有发现这个问题，请在demo中测试，看看是否有此问题。

**Comment by SmileZXLee** [comment]
> > 这个为系统行为，z-paging无法干预，建议使用系统导航栏。或是设置 input 的`adjust-position`属性，禁止上推页面。
> 
> 好的，还有个问题是nvue 的情况下当没有聊天记录的时候 top插槽里的内容也无法正常显示

经过测试没有发现这个问题，请在demo中测试，看看是否有此问题。

**Comment by fe-room** [comment]
> > > 这个为系统行为，z-paging无法干预，建议使用系统导航栏。或是设置 input 的`adjust-position`属性，禁止上推页面。
> > 
> > 
> > 好的，还有个问题是nvue 的情况下当没有聊天记录的时候 top插槽里的内容也无法正常显示
> 
> 经过测试没有发现这个问题，请在demo中测试，看看是否有此问题。
好吧 非常感谢。我这边用我的例子 把源码的v-if的判断去就正常展示了。不知道是不是我的编辑器版本问题（不是最新版）。 我看到您在文档是上写的use-chat-record-mode 建议同时开启页面滚动(设置use-page-scroll为true)，可一定程度优化页面闪动/跳动问题。我看到nvue的demo 上是没有的  我在nvue模式上使用的话 会出现更大的问题。

**Comment by SmileZXLee** [comment]
什么更大的问题

**Comment by fe-room** [comment]
> 什么更大的问题

底部插槽防止的输入框位置会错乱
