### ISSUE TITLE
vue3下常规使用安卓模拟器会提示内存溢出的报错

### ISSUE THREAD

**Issue by html546** [SmileZXLee/uni-z-paging#37]
![image](https://user-images.githubusercontent.com/24297621/191891097-2ca89210-ce78-4258-a85e-13486ff1e130.png)
初步定位原因是在z-paging.vue中第99行引入的zp-public-virtual-cell这个组件未注册所导致的，所以为了规避这个报错只能先将这个组件注释掉了，在h5中只是黄色的警告不影响正常的使用
![image](https://user-images.githubusercontent.com/24297621/191891237-d91540a3-6383-4131-a4bb-849d223063aa.png)
，但是在安卓机上不行。版本2.4.0

**Comment by SmileZXLee** [comment]
你是不是通过npm安装的呢？

**Comment by SmileZXLee** [comment]
目前收到几个反馈，似乎npm上才有这个问题。如果是这样的话，我就在npm版本单独注释。需要再打开。

**Comment by html546** [comment]
不是npm安装，是直接导入的uni_modules插件使用的

**Comment by SmileZXLee** [comment]
好的，感谢反馈！！
