### ISSUE TITLE
【严重bug】小程序组件中使用z-paging时，scrollIntoViewById等方法无效，原因是........

### ISSUE THREAD

**Issue by echofly** [SmileZXLee/uni-z-paging#43]
【严重bug】小程序**组件**中使用z-paging时，scrollIntoViewById等方法无效，原因是因为inThis要为true，限制查询范围为当前组件，**并且还有另外一个bug**，`uni.createSelectorQuery().in(this)`中的`this`需要从组件中传过来，而不是直接写this，**因为这个this是该函数的上下文，不是组件的上下文**，看下图：
![image](https://user-images.githubusercontent.com/36875450/211981913-c18280c1-ecf4-4494-92fa-c9b199a69d69.png)

![image](https://user-images.githubusercontent.com/36875450/211979178-3f9310b3-b07f-4f3e-8716-11f6b57223c9.png)

**Comment by SmileZXLee** [comment]
我试了scrollIntoViewById有效的。你指的小程序是指 微信小程序吗。而且这个函数中的this本身就是组件的this而非函数的this的。并且我测试了相关功能都是正常的

**Comment by echofly** [comment]
> 我试了scrollIntoViewById有效的。你指的小程序是指 微信小程序吗。而且这个函数中的this本身就是组件的this而非函数的this的。并且我测试了相关功能都是正常的

前提是一定要微信小程序**组件**中使用z-paging，而非页面中。那个this肯定不是组件的this，你了解下js的this指向原理就知道了。

**Comment by echofly** [comment]
我猜你测试的时候是在页面使用z-paging测试的

**Comment by SmileZXLee** [comment]
提供有问题的demo

**Comment by SmileZXLee** [comment]
或者你直接在源码基础上修改，提交mr也可以的

**Comment by echofly** [comment]
> 或者你直接在源码基础上修改，提交mr也可以的

不行，这个bug影响到的方法应该比较多，我对全局代码不熟，需要你自己掌控，我晚点给你个demo吧

**Comment by SmileZXLee** [comment]
> 

不管在哪里都是组件的this的

**Comment by SmileZXLee** [comment]
> > 或者你直接在源码基础上修改，提交mr也可以的
> 
> 不行，这个bug影响到的方法应该比较多，我对全局代码不熟，需要你自己掌控，我晚点给你个demo吧

ok

**Comment by SmileZXLee** [comment]
> > 或者你直接在源码基础上修改，提交mr也可以的
> 
> 不行，这个bug影响到的方法应该比较多，我对全局代码不熟，需要你自己掌控，我晚点给你个demo吧

ok

**Comment by echofly** [comment]
这是[demo](https://github.com/echofly/uni-z-paging)地址，就是在你的项目pages目录下加了个issue43-test页面，编译后用开发者工具打开即可测试。点击“滚动到3”按钮是无效的，你调试后就会发现最终问题是没把组件中的this传过去

**Comment by echofly** [comment]
这是我在自己项目中的临时解决方案，仅供参考，就是在方法中把组件的this传过去了
![image](https://user-images.githubusercontent.com/36875450/215717423-3cf0b9cf-a152-4b2b-a53b-24ff22f06be3.png)
![image](https://user-images.githubusercontent.com/36875450/215718019-bedad88e-992b-462a-aeb2-40e945968bdd.png)
![image](https://user-images.githubusercontent.com/36875450/215719023-e0086c8c-5c48-4e69-b7aa-cdc13da959be.png)
![image](https://user-images.githubusercontent.com/36875450/215718582-39d35ad7-fff1-4cbf-8404-c0d4cdf0a914.png)

**Comment by SmileZXLee** [comment]
这里的this的确是组件的this，而非函数的this。只是这里的this应当传z-paging组件的父组件的this。这样的话用this.$parents（这里的this就是z-paging组件的this而非函数的this）就好了不用外面再传一个context进来。不过这样不同的平台好像也有差异，我再多试试看看。感谢！

**Comment by SmileZXLee** [comment]
我明白了，你上面说的组件是指z-paging的父组件。我理解的是z-paging组件。理解有差异

**Comment by echofly** [comment]
是的，是z-paging的父组件的this

**Comment by SmileZXLee** [comment]
嗯嗯，感谢反馈。我修复一下这个问题！！
