### ISSUE TITLE
加载中模态框不显示

### ISSUE THREAD

**Issue by chi8708** [SmileZXLee/uni-z-paging#44]
vue2 +z-paging2.5.3 数据加载正常，获取数据时， 加载中...模态框不显示，如何解决

**Comment by SmileZXLee** [comment]
实测会显示；是什么平台下不显示呢

**Comment by chi8708** [comment]
移动平台都不显示，加了:auto-show-system-loading="true" 能显示。可不可以控制上拉或下拉刷新也显示

**Comment by SmileZXLee** [comment]
请在封装的请求中控制是否显示loading，一般是封装的请求中，统一的请求拦截器处理的。z-paging内置的在滚动到底部加载更多的时候不会显示系统loading，因为已经可以看到底部的【加载中...】字样了，没有必要再多显示一个全屏的加载中，属于画蛇添足了。

**Comment by chi8708** [comment]
好的 谢谢

**Comment by SmileZXLee** [comment]
不客气
