### ISSUE TITLE
在vue3 + ts + vite 环境下，运行在iOS iPhone 14 Pro Max模拟器上，报下面错误

### ISSUE THREAD

**Issue by Antduo** [SmileZXLee/uni-z-paging#49]
11:30:11.904 at <ZPaging modelValue=  onUpdate:modelValue=fn onQuery=fn<queryList>  ... >
11:30:11.910 at <Index __pageId=1 __pagePath="pages/index/index" __pageQuery= {}  ... > __WARN
11:30:11.915 TypeError: vue.undefined is not a function. (In 'vue.undefined(_ctx.wxsPropType)', 'vue.undefined' is undefined) __ERROR
11:30:11.915 at <ZPaging modelValue= [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] onUpdate:modelValue=fn onQuery=fn<queryList>  ... >
11:30:11.921 at <Index __pageId=1 __pagePath="pages/index/index" __pageQuery= {}  ... > __WARN
11:30:11.926 TypeError: vue.undefined is not a function. (In 'vue.undefined(_ctx.wxsPropType)', 'vue.undefined' is undefined) __ERROR
11:30:11.932 at <ZPaging modelValue= [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] onUpdate:modelValue=fn onQuery=fn<queryList>  ... >
11:30:11.932 at <Index __pageId=1 __pagePath="pages/index/index" __pageQuery= {}  ... > __WARN
11:30:11.939 TypeError: We.setAttribute is not a function. (In 'We.setAttribute(R.ATTR_V_OWNER_ID,it.uid)', 'We.setAttribute' is undefined) __ERROR
11:30:11.940 at <ZPaging modelValue= [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] onUpdate:modelValue=fn onQuery=fn<queryList>  ... >
11:30:11.949 at <Index __pageId=1 __pagePath="pages/index/index" __pageQuery= {}  ... > __WARN
11:30:11.956 TypeError: vue.undefined is not a function. (In 'vue.undefined(_ctx.wxsPropType)', 'vue.undefined' is undefined) __ERROR

**Comment by SmileZXLee** [comment]
可否提供一个可复现的demo以便我排查，感谢

**Comment by Antduo** [comment]
> 可否提供一个可复现的demo以便我排查，感谢

代码地址：https://gitee.com/wbt_326/vue3-ts-demo.git
网络请求目录：src/pages/index/hook.ts

**Comment by SmileZXLee** [comment]
感谢，经查是你项目中uniapp版本过旧导致的。使用命令：`npx @dcloudio/uvm`将uniapp更新至最新即可。

**Comment by Antduo** [comment]
> > 可否提供一个可复现的demo以便我排查，感谢
> 
> 代码地址：https://gitee.com/wbt_326/vue3-ts-demo.git 网络请求目录：src/pages/index/hook.ts

**Comment by Antduo** [comment]
> > > 可否提供一个可复现的demo以便我排查，感谢
> > 
> > 
> > 代码地址：https://gitee.com/wbt_326/vue3-ts-demo.git 网络请求目录：src/pages/index/hook.ts

太感谢了，升级一下运行正常了

**Comment by Antduo** [comment]
> 感谢，经查是你项目中uniapp版本过旧导致的。使用命令：`npx @dcloudio/uvm`将uniapp更新至最新即可。

太感谢了，升级一下运行正常了

**Comment by mmxxfff** [comment]
想问一下，最后那个 在 vue.config.js中添加配置 module.exports = {
	transpileDependencies: ['z-paging']
}，如果是在vite.config.js中应该怎么添加呢？不需要在创建一个 vue.config.js把
