### ISSUE TITLE
使用贵插件在安卓和ios正常，在h5中提示Uncaught (in promise) TypeError: Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by cczuwangkun** [SmileZXLee/uni-z-paging#51]
![image](https://user-images.githubusercontent.com/31639968/228751677-22dbae6f-e52b-446d-8917-f42c17909041.png)
![image](https://user-images.githubusercontent.com/31639968/228751726-123ea2e5-399c-4562-883e-24401e0963c9.png)

**Comment by SmileZXLee** [comment]
打印this_.$refs.paging 看看为什么是空的
