### ISSUE TITLE
TypeError: Cannot set property 'currentInstance' of undefined

### ISSUE THREAD

**Issue by yabowang** [SmileZXLee/uni-z-paging#56]
[Vue warn]: Error in callback for immediate watcher "wxsPropType": "TypeError: Cannot set property 'currentInstance' of undefined"

found in

---> <ZPaging> at uni_modules/z-paging/components/z-paging/z-paging.vue
       <ZPagingSwiper> at uni_modules/z-paging/components/z-paging-swiper/z-paging-swiper.vue
         at pages/certificate/my_certificate.vue
14:14:14.303 [system]TypeError: Cannot set property 'currentInstance' of undefined
    at Object.propObserver [as wxsPropType] (webpack-internal:///ZJSA:10:24)
    at VueComponent.vnode.$wxsWatches.<computed>.oldWxsWatches.<computed>.vnode.context.$watch.immediate

**Comment by SmileZXLee** [comment]
更新z-paging即可解决
