### ISSUE TITLE
想要通过请求接口的响应来决定pageSize该怎么做？

### ISSUE THREAD

**Issue by qq958691165** [SmileZXLee/uni-z-paging#57]
如题

**Comment by qq958691165** [comment]
不是请求分页的配置，而是能不能在每次请求数据时都根据返回的pageSize和total来决定是否有下一页

**Comment by qq958691165** [comment]
不是请求分页的配置，而是能不是在每次请求数据时都根据返回的pageSize和total来决定是否有下一页

**Comment by SmileZXLee** [comment]
可以的，使用completeByTotal代替complete即可：
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/29226317/235121208-c5152f7f-2309-4def-a823-9efb3cdd4f4d.png">

**Comment by qq958691165** [comment]
试过了，但不知道是不是在chatMode下不行，default-page-size为15，然后请求之后把default-page-size改为5了，然后再调用completeByTotal，但是之后就无法加载下一页数据

**Comment by qq958691165** [comment]
解决了，是内容高度不够的问题
