### ISSUE TITLE
Promise异常第二次触发后不能捕获到

### ISSUE THREAD

**Issue by joriscai** [SmileZXLee/uni-z-paging#58]
出现问题如图，只要是设置为失败就会导致全局的Uncaught (in promise)
<img width="1352" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/17852005/b64abe54-8bc2-40a3-809e-8d5ede145c77">
调用代码如下：第一次能catch到，第二次还是报全局的Uncaught (in promise)
![image](https://github.com/SmileZXLee/uni-z-paging/assets/17852005/b48d96bd-4ea6-4e39-ac4f-53c8faf94864)

这样的设计应该不合理，用vue-cli来跑代码就会提示报错遮挡了，虽然可以关掉。
还有一种情况，如何有加js日志上报的，这里的报错也会导致每次的日志上报，并且这样的报错也很难定位报错的位置和原因。

**Comment by SmileZXLee** [comment]
感谢反馈，这是一个bug，将在下一个版本中进行修复

**Comment by SmileZXLee** [comment]
经查这个catch是触发`reload`时的catch，`reload`触发时若加载失败会触发其catch，如果没有正确捕获将在控制台抛出异常。我目前的方案是在z-paging内部点击空数据“【重新加载】”按钮处的reload添加catch处理，你如果在页面中有调用reload也应当添加catch，另外reject处我将添加对应的z-paging标识的报错信息，如果有日志上报，可以根据报错信息过滤后再上传

**Comment by SmileZXLee** [comment]
经查这个catch是触发`reload`时的catch，`reload`触发时若加载失败会触发其catch，如果没有正确捕获将在控制台抛出异常。我目前的方案是在z-paging内部点击空数据“【重新加载】”按钮处的`reload`添加catch处理，你如果在页面中有调用`reload`也应当添加catch，另外reject处我将添加对应的z-paging标识的报错信息，如果有日志上报，可以根据报错信息过滤后再上传

**Comment by SmileZXLee** [comment]
代码已更新，请使用此仓库中的最新z-paging组件代码尝试是否能解决此issue
