### ISSUE TITLE
希望支持一个索引列表

### ISSUE THREAD

**Issue by didnhdj2** [SmileZXLee/uni-z-paging#59]
希望支持一个索引列表

**Comment by SmileZXLee** [comment]
这个不属于分页的范畴，也不适合搭配分页一起使用。可以在z-paging内插入第三方的索引列表来实现，如果所有边缘需求都支持的话插件会变得极其庞大，因此建议根据需求引入定制化需求的其他插件。

**Comment by didnhdj2** [comment]
好嘞，感谢回复

**Comment by SmileZXLee** [comment]
不客气~
