### ISSUE TITLE
数据显示不到屏幕底部的上拉，是不是只能用scroll-view的模式

### ISSUE THREAD

**Issue by hugetiny** [SmileZXLee/uni-z-paging#6]
数据显示不到屏幕底部的上拉，是不是只能用scroll-view的模式？

就是如果页面包括初始化，每次上拉只加载一条数据（数据显示没到底部的情况）
是不是只能用scroll-view的模式
还是说设置body高度把屏幕撑满比较好？

**Comment by SmileZXLee** [comment]
数据未铺满屏幕，目前仅支持点击加载更多，只有超出滚动区域，才可以滚动到底部。如果是数据不满屏幕，自动占满屏幕，也是同样无法滚动到底部的，只有内容高度>页面高度+底部加载更多view高度才可以滚动到底部，但是那样体验会很奇怪。还有一种是底部上拉加载更多，类似下拉刷新。但是目前暂无添加底部上拉加载更多的计划，因此当页面内容不满屏时，目前仅支持点击加载更多。

**Comment by hugetiny** [comment]
用过ios上的clear吗？就是一个手势操作的todo app，我想实现那样的效果：上拉添加一条新todo
然而todo少的时候一般都铺不满屏幕的

**Comment by hugetiny** [comment]
我想到了一个奇淫技巧！开始时获取body高度，用css class样式控制。
透明的数据正好撑满页面，加载一条就删除一条透明数据，感觉可以啊

**Comment by SmileZXLee** [comment]
我下载了clear，发现要实现这种效果不宜使用z-paging，因为它本身只有手势，没有下拉刷新、滚动到底部加载更多。实际上只有下拉和上拉手势，并且做出相应的手势。要实现这个效果只要在page那边添加一个全屏的view，并在上面添加@touchmove等事件，处理下拉和上拉的情况即可。
