### ISSUE TITLE
聊天记录模式，bottom插槽中组件问题

### ISSUE THREAD

**Issue by mmdlsu** [SmileZXLee/uni-z-paging#60]
bottom插槽中组件里面的textarea无法滚动，不在插槽内的可以滚动，很奇怪的bug
![screenshots](https://github.com/SmileZXLee/uni-z-paging/assets/57515771/d895a9df-2bd3-405a-b80b-022e73ae8d31)

**Comment by SmileZXLee** [comment]
这是vue2还是vue3；是微信小程序吗？我在demo中试了一下在微信小程序和h5中，textarea在slot="bottom"内都可以正常滚动的

**Comment by mmdlsu** [comment]
是vue2在APP或者h5不行

**Comment by mmdlsu** [comment]
你好，我是在:fixed="false" 情况下会有这种情况，测试了demo确实没问题，把use-page-scroll 去掉设置:fixed="false" 就有这个问题

**Comment by mmdlsu** [comment]
![image](https://github.com/SmileZXLee/uni-z-paging/assets/57515771/fba30233-51f3-49ad-a5a0-4522788f4364)

**Comment by SmileZXLee** [comment]
在插入的bottom中，添加`@touchmove.stop`阻止事件冒泡即可。例如：
<img width="794" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/514ff19b-40b1-4ddb-97d4-5ba1ff9499b0">

**Comment by mmdlsu** [comment]
感谢，原来是这样的问题

**Comment by SmileZXLee** [comment]
不客气
