### ISSUE TITLE
自定义empty的slot的时候，#empty="{isLoadFailed}"拿取isLoadFailed变量，提示isLoadFailed is not defined，小程序环境

### ISSUE THREAD

**Issue by html546** [SmileZXLee/uni-z-paging#62]
自定义empty的slot的时候，#empty="{isLoadFailed}"拿取isLoadFailed变量，提示isLoadFailed is not defined，小程序环境

**Comment by SmileZXLee** [comment]
<img width="1292" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/74a35149-7b19-48ef-a869-3e717cc787b7">
我试了一下 没有问题

**Comment by SmileZXLee** [comment]
注意 #empty="{isLoadFailed}" 一定要放在template标签上
