### ISSUE TITLE
在uni平台使用z-pageing的打包到h5 报错误pagingRenderjs is not defined

### ISSUE THREAD

**Issue by w675179089** [SmileZXLee/uni-z-paging#67]
**编译平台**
使用HbuilderX还是npm方式编译出现的问题？（如：HbuilderX）
npm

**VUE版本**
在vue2还是vue3中出现的问题，是nvue还是vue？（如：vue2+nvue）
vue2
**运行平台**
在运行到哪个平台中出现的问题？（如：App、微信小程序、h5）
h5

**z-paging版本**
在哪个版本的z-paging中出现的问题？
2.3.4
**问题描述**
请详细描述问题，最好说明复现步骤，尽可能附上代码或截图
<img width="802" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/26165417/1d7c3daa-5e51-4db7-9189-d4ada911457d">

**Comment by SmileZXLee** [comment]
未能复现此问题，请尝试demo是否有此问题
