### ISSUE TITLE
use-page-scroll 问题

### ISSUE THREAD

**Issue by xiaojia21190** [SmileZXLee/uni-z-paging#7]
当 use-page-scroll  存在时候, 使用了  slot="top" 固定头 后, 下方列表区域 无法滚动

**Comment by xiaojia21190** [comment]
![image](https://user-images.githubusercontent.com/16084693/125248550-be8b6180-e326-11eb-8238-f1b94c941094.png)

**Comment by SmileZXLee** [comment]
请提供版本号，建议更新到最新版本后再次尝试。  
下载并运行demo，查看是否有这一问题，我在demo中尝试是正常的。  
如果问题未解决，可以加一下qq群：790460711，提供更详尽的描述和代码片段以便我排查，感谢。
