### ISSUE TITLE
虚拟列表如何添加数据

### ISSUE THREAD

**Issue by PaulDuChina** [SmileZXLee/uni-z-paging#71]
感谢作者提供这么好的组件，我有个用法不知道怎么实现

问题： 页面上有个新增的按钮，点击后，虚拟列表的数据会添加一个，我目前使用的用法是
`this.$refs.paging.totalData.unshift()`
造成的问题 如下，会生成一个zp-id-undefined的节点
![image](https://github.com/SmileZXLee/uni-z-paging/assets/30306628/ab888883-166c-4dc6-a541-dc32d78ce577)
期望值 ： 期望得到正确的向虚拟列表中添加数据的办法

**Comment by PaulDuChina** [comment]
查看源码，发现有一个是删除后调用的，目前没发现如何新增。期望尽快得到 作者的回复 
![image](https://github.com/SmileZXLee/uni-z-paging/assets/30306628/405bf21c-966e-4ecc-b8b3-a7172232e3fd)

**Comment by SmileZXLee** [comment]
可以通过
<img width="1018" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/011efb20-f950-46c4-a9f6-bf2fae9010fd">
this.$refs.paging.totalData.unshift()也是可以的；
`zp-id-undefined`问题会存在，但不影响虚拟列表的正常渲染，可以忽略即可
