### ISSUE TITLE
使用了原生微信的自定义custom-tab-bar 我该如何计算高度

### ISSUE THREAD

**Issue by xianyu21** [SmileZXLee/uni-z-paging#73]
** 请描述您在使用期间遇到的疑问 **
![image](https://github.com/SmileZXLee/uni-z-paging/assets/35288214/7114250e-7b60-461b-a410-165b44317e5e)
我还使用了sticky-swiper-next-item 发现怎么去计算都无法的到正确的高度值

**Comment by SmileZXLee** [comment]
固定在顶部的放在slot="top"内即可
<img width="1091" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/010c9273-5ccf-474e-bbdb-4e7a840a769f">

**Comment by SmileZXLee** [comment]
tabbar的话放在slot="bottom"内。也是类似的
<img width="1033" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/1ebbeaaa-1da1-400a-afe3-1b45529c9e2a">

**Comment by xianyu21** [comment]
这是关于原生微信的自定义custom-tab-bar描述
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html[](url)

是放不到slot="bottom" 也就无法计算高度

而且我的头部导航栏以及轮播图是使用固定定位的 只有在滑动的时候取消 不知道是不是这个原因影响?
![image](https://github.com/SmileZXLee/uni-z-paging/assets/35288214/2b5fcc40-538a-4dc0-9c82-17ffc98167bd)
![image](https://github.com/SmileZXLee/uni-z-paging/assets/35288214/6ada11e7-c676-4e97-9a4f-99de228ca034)

**Comment by SmileZXLee** [comment]
这个是因为你固定在顶部的view没有放在slot="top"内导致的，需要把它们放进去即可。
<img width="985" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/f8799e2b-225b-41b9-b566-b00abe217223">

**Comment by Muspcn** [comment]
这个头部没有配置项关掉吗，找了很多相关的单词都没见到有，
![Image](https://github.com/user-attachments/assets/29998c0e-93b3-43dd-8089-59706d7f656d)
