### ISSUE TITLE
addChatRecordData在nvue中问题

### ISSUE THREAD

**Issue by rockPrince** [SmileZXLee/uni-z-paging#76]
**编译平台**
npm

**VUE版本**
vue2 + nvue

**运行平台**
h5

**z-paging版本**
2.5.8

**问题描述**
在示例项目pages/chat-history-demo-n/chat-history-demo-n
如果调用 addChatRecordData 后100-300毫秒之内再调用一次addChatRecordData 
页面无法滚动到页面最下方
<img width="524" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/13901032/af799852-7587-487d-bbd6-08cc524f07f8">
<img width="540" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/13901032/fadf732a-49a8-47dc-9028-7ca41c5429f8">

**Comment by SmileZXLee** [comment]
下载`v2.7.0`版本再试下
