### ISSUE TITLE
nvue 聊天记录模式,使用 script setup 消息颠倒

### ISSUE THREAD

**Issue by ShineKidd** [SmileZXLee/uni-z-paging#77]
**编译平台**
HbuilderX

**VUE版本**
vue3

**运行平台**
App

**z-paging版本**
2.5.8

**问题描述**
把 pages/chat-history-demo-n/chat-history-demo-n.vue 文件改写成 `<script setup>` 写法，渲染结果如下图

![image](https://github.com/SmileZXLee/uni-z-paging/assets/25340861/2dd2b003-2cdb-425b-9852-d071935b438e)

**Comment by SmileZXLee** [comment]
猜测是修改以后cellStyle没设置。请下载demo中的vue3demo，有setup的示例写法
<img width="341" alt="image" src="https://github.com/SmileZXLee/uni-z-paging/assets/29226317/a1fb27a8-9a90-45ce-b3db-3f13d3ca2684">
