### ISSUE TITLE
1、回到顶部无效

### ISSUE THREAD

**Issue by wzhsh90** [SmileZXLee/uni-z-paging#78]
vue3+微信小程序+v2.5.7 

出现回到顶部按钮后，点击只能第1次回到顶部。后面滚动再点击无效。

调整：修改scroller.js 267 行，this.scrollTop =Math.random();

**Comment by SmileZXLee** [comment]
是否同时使用的uview-plus，目前有几个类似反馈是main.js中use了uview-plus导致的，因为uniapp官方的滚动到顶部和z-paging是一致的，然后测试了官方的scroll-view滚动到顶部的demo在uview-plus也有相同的问题

**Comment by wzhsh90** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 晚上10:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SmileZXLee/uni-z-paging] 1、回到顶部无效 (Issue #78)




 
是否同时使用的uview-plus，目前有几个类似反馈是main.js中use了uview-plus导致的，因为uniapp官方的滚动到顶部和z-paging是一致的，然后测试了官方的scroll-view滚动到顶部的demo在uview-plus也有相同的问题

**Comment by SmileZXLee** [comment]
好的 感谢反馈！

**Comment by SmileZXLee** [comment]
#91

**Comment by SmileZXLee** [comment]
uview-plus作者已处理：https://github.com/ijry/uview-plus/issues/265#issuecomment-2100758151
