### ISSUE TITLE
.zp-n-refresh-container  样式 不应该固定宽度

### ISSUE THREAD

**Issue by wasdokij** [SmileZXLee/uni-z-paging#8]
.zp-n-refresh-container {
	/* #ifndef APP-NVUE */
	display: flex;
	/* #endif */
	justify-content: center;
	width: 750rpx;  /* 这里不应该固定宽度， 否则，非750宽度的下的 下拉刷新会歪的*/
}

**Comment by SmileZXLee** [comment]
`750rpx`就代表着宽度100%了，rpx会随着屏幕尺寸的变化而变化。nvue中无法使用百分比，因此使用`750rpx`。
