### ISSUE TITLE
当通过complete传进去的数组长度小于pageSize时，则判定为没有更多了

### ISSUE THREAD

**Issue by wzhsh90** [SmileZXLee/uni-z-paging#80]
vue3+zpaging:2.5.8

这个算法是错误的，当数据返回长度与pageSize 相等时就有问题。

**Comment by wzhsh90** [comment]
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/29226317/265384218-3ec0a642-171d-425a-9217-a75cd0f10378.png">

这个方法与逻辑我清楚，但这个算法是错误的，不应该这样来做设计算法。
可以参考一下
1、layui 的table 处理 
2、mescroll 的是否没有数据

**Comment by SmileZXLee** [comment]
你的意思是应该传total进去，根据total判断吗？

**Comment by wzhsh90** [comment]
![image](https://github.com/SmileZXLee/uni-z-paging/assets/16187191/3d8a1023-137e-436f-a4eb-424a4a9e3a6e)

**Comment by SmileZXLee** [comment]
这个就是根据total判断的 z-paging也是支持的。使用`completeByTotal`即可。根据总页数判断分页结束的场景很少，如果需要的话也可以支持。这些都可以自由选择的，不是强制使用complete。

**Comment by wzhsh90** [comment]
我想表达是，应该调整一个complete 方法，不然很容易出现bug.

目前complete 算法是不严谨的，另外还可能带来无限加载。

**Comment by SmileZXLee** [comment]
你指的不严谨具体是哪些方面？就是有无限加载的可能吧？
无限加载可以处理，就是判断一下新旧数据是否一样，但是这样比较耗费性能。
可以提交pr，如果合理的话我合并到master当中，目前complete就是专门针对传统的，超过pageNum返回空数组的情况
