### ISSUE TITLE
H5和android的键盘弹起后，聊天界面无法自动收起或缩短高度

### ISSUE THREAD

**Issue by idbeny** [SmileZXLee/uni-z-paging#81]
**编译平台**
使用HbuilderX还是npm方式编译出现的问题？（如：HbuilderX）
HbuilderX

**VUE版本**
在vue2还是vue3中出现的问题，是nvue还是vue？（如：vue2+nvue）
vue2

**运行平台**
在运行到哪个平台中出现的问题？（如：App、微信小程序、h5）
H5和App

**z-paging版本**
在哪个版本的z-paging中出现的问题？
2.5.8

**问题描述**
请详细描述问题，最好说明复现步骤，尽可能附上代码或截图
使用聊天模式时，H5和android的键盘弹起后，聊天界面无法自动收起或缩短高度。
使用的是Github提供的Demo。

**Comment by SmileZXLee** [comment]
`v2.7.0`带来了全新设计的聊天记录模式，完全解决了聊天记录模式滚动加载更多闪动和微信小程序中导航栏被顶上去的问题！欢迎更新体验！
