### ISSUE TITLE
自定义tabbar h5 高度如何重新计算

### ISSUE THREAD

**Issue by Rayzworld** [SmileZXLee/uni-z-paging#82]
** 请描述您在使用期间遇到的疑问 **
![image](https://github.com/SmileZXLee/uni-z-paging/assets/9161921/2df8486a-f1dc-4658-aa69-d518ac003e58)
h

![image](https://github.com/SmileZXLee/uni-z-paging/assets/9161921/d25bd5b3-4f36-40ad-ab33-44751550643f)

导航和tabbar都是扔在插槽中 没有设置fixed
但是h5上会多出来一块tabbar高度 小程序上正常显示
![image](https://github.com/SmileZXLee/uni-z-paging/assets/9161921/793abd1b-68bf-4cfd-ad3c-90de89142544)
如果把page.json中自定义tabbar去了 显示就对了
有没有方法能让它重新走一遍高度

**Comment by SmileZXLee** [comment]
检查元素看下，h5上会多出来一块tabbar高度，是什么，是不是自定义tabbar自带的呢
