### ISSUE TITLE
Cannot read property 'reload' of null

### ISSUE THREAD

**Issue by xiaotan0317** [SmileZXLee/uni-z-paging#86]
**编译平台**
使用HbuilderX还是npm方式编译出现的问题？（如：HbuilderX）
npm
**VUE版本**
在vue2还是vue3中出现的问题，是nvue还是vue？（如：vue2+nvue）
vue3
**运行平台**
在运行到哪个平台中出现的问题？（如：App、微信小程序、h5）
微信小程序
**z-paging版本**
在哪个版本的z-paging中出现的问题？

**问题描述**
请详细描述问题，最好说明复现步骤，尽可能附上代码或截图
:auto="false"禁止自动执行，在onShow中执行paging.value.reload()，报Cannot read property 'reload' of null

**Comment by SmileZXLee** [comment]
在onShow中调用reload方法需要用nextTick包住，因为onShow的时候组件还没渲染，因此paging.value是空的
