### ISSUE TITLE
slot=“top”顶部采用uview的搜索框，在微信小程序快速上拉会造成搜索框placeholder短暂消失

### ISSUE THREAD

**Issue by AaronChuzb** [SmileZXLee/uni-z-paging#9]
这个问题很怪异，在app端挺正常，微信小程序存在这个问题。
`<z-paging ref="paging" v-model="dataList" @query="getData" :default-page-size="5" :auto-show-back-to-top="true" :refresher-end-bounce-enabled="true" :refresher-complete-delay="300">
      <view class="options" slot="top">
        <view class="search">
          <u-search placeholder="请输入关键词" v-model="keyword" :clearabled="true" :show-action="true" action-text="搜索" @custom="$refs.paging.reload()" @search="$refs.paging.reload()" :animation="false"></u-search>
        </view>
        <view class="search" style="margin-top: 15rpx">
          <u-subsection :list="list" :current="0" @change="typeChange"></u-subsection>
        </view>
      </view>
      <remain :page-data="item" v-for="(item, index) in dataList" :key="index"></remain>
    </z-paging>`

**Comment by SmileZXLee** [comment]
你好，我在微信小程序中尝试未能复现此问题。如果方便的话可以提供一个简要的可复现的demo以便我排查问题，感谢。

**Comment by AaronChuzb** [comment]
> 你好，我在微信小程序中尝试未能复现此问题。如果方便的话可以提供一个简要的可复现的demo以便我排查问题，感谢。

你好，感谢你的回复，我已将问题复现并上传在此仓库：https://github.com/AaronChuzb/z-paging-demo.git

**Comment by SmileZXLee** [comment]
> > 你好，我在微信小程序中尝试未能复现此问题。如果方便的话可以提供一个简要的可复现的demo以便我排查问题，感谢。
> 
> 你好，感谢你的回复，我已将问题复现并上传在此仓库：https://github.com/AaronChuzb/z-paging-demo.git

收到，谢谢

**Comment by SmileZXLee** [comment]
> > 你好，我在微信小程序中尝试未能复现此问题。如果方便的话可以提供一个简要的可复现的demo以便我排查问题，感谢。
> 
> 你好，感谢你的回复，我已将问题复现并上传在此仓库：https://github.com/AaronChuzb/z-paging-demo.git

文件缺失
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/29226317/134791146-f9ae9f45-c3f3-40a1-9cf1-3332b2cd0e18.png">

**Comment by SmileZXLee** [comment]
你好，经过排查，在微信小程序中，若input是通过slot方式插入到子组件中时，滚动列表会导致input内容消失，原因不明，可能是小程序或者uni的bug。解决方案就是不使用slot插入，我在你的demo基础上进行了修改，可以下载参考一下。  
[z-paging-demo-master.zip](https://github.com/SmileZXLee/uni-z-paging/files/7230859/z-paging-demo-master.zip)

**Comment by AaronChuzb** [comment]
> 你好，经过排查，在微信小程序中，若input是通过slot方式插入到子组件中时，滚动列表会导致input内容消失，原因不明，可能是小程序或者uni的bug。解决方案就是不使用slot插入，我在你的demo基础上进行了修改，可以下载参考一下。
> [z-paging-demo-master.zip](https://github.com/SmileZXLee/uni-z-paging/files/7230859/z-paging-demo-master.zip)

收到👌🏻，感谢你的回复，这个组件十分不错。
