### ISSUE TITLE
slot='top' 插槽在钉钉小程序上不展示

### ISSUE THREAD

**Issue by MgGaHui** [SmileZXLee/uni-z-paging#95]
**编译平台**
HbuilderX

**VUE版本**
vue2

**运行平台**
钉钉小程序

**z-paging版本**
2.6.0

**问题描述**
在钉钉小程序上不展示top插槽内容，经过排查，
_问题地方_在于`zslots.top`值的判断
![image](https://github.com/SmileZXLee/uni-z-paging/assets/44692259/b16679c9-045f-46cf-a808-362159e64ae4)

_源码中_`zslots.top`在微信小程序上有值，在钉钉小程序上没有值

_微信小程序上取值结果：_ ![image](https://github.com/SmileZXLee/uni-z-paging/assets/44692259/e21b6b74-9aa3-4d0e-b799-a469b8fc47d9)

_钉钉小程序上取值结果：_ ![image](https://github.com/SmileZXLee/uni-z-paging/assets/44692259/36236c41-000b-4ce8-addf-03f26797de64)

**Comment by SmileZXLee** [comment]
请点击详情并勾选component2

**Comment by MgGaHui** [comment]
感谢，问题解决
