### ISSUE TITLE
nvue vue2 局部滚动的问题

### ISSUE THREAD

**Issue by op89as** [SmileZXLee/uni-z-paging#97]
我的一个nvue页面， 有ABC三个内容撑开了高度出现页面滚动，但是B页面使用了z-paging且设置了 :fixed="false"属性 但是实际真机效果出现页面可以滚动 但是B区域无法滚动。

**Comment by SmileZXLee** [comment]
尝试设置页面滚动：`:use-page-scroll="true"`

**Comment by op89as** [comment]
> 尝试设置页面滚动：`:use-page-scroll="true"`

试了很多方式都不行 最后用了这个方案 想问一下这个是nvue的限制么 页面滚动和区域滚动不能一起

**Comment by SmileZXLee** [comment]
原因暂不明，我有空看看
